---

- name: add Docker GPG key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: add Docker CE repository
  get_url:
    url: https://download.docker.com/linux/{{ (ansible_distribution == "Fedora") | ternary("fedora", "centos") }}/docker-ce.repo
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644

- name: install dependencies
  yum:
    name:
      - e2fsprogs
    state: present

- name: install Docker package
  yum:
    name:
      - python-docker
      - docker-ce
    state: present
